"""add model_version to analyses

Revision ID: 50d9509d427d
Revises: 82344daa84e2
Create Date: 2026-09-14 21:24:37.712138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d9509d427d'
down_revision: Union[str, Sequence[str], None] = '82344daa84e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('model_version', sa.String(), server_default='unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'model_version')
    # ### end Alembic commands ###
